### ISSUE TITLE
PCV

### ISSUE THREAD

**Issue by agustinvinao** [hobby-kube/guide#36]
Im trying to create a PCV with this yml
```
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: portworx
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: postgres-data-staging
   namespace: lb-staging
spec:
  storageClassName: portworx
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

but im getting this error `Failed to provision volume with StorageClass "portworx": services "portworx-service" not found`

```
Name:          postgres-data-staging
Namespace:     lb-staging
StorageClass:  portworx
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"postgres-data-staging","namespace":"lb-staging"},"spec":{"access...
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/portworx-volume
Capacity:
Access Modes:
Events:
  Type     Reason              Age              From                         Message
  ----     ------              ----             ----                         -------
  Warning  ProvisioningFailed  1s (x2 over 6s)  persistentvolume-controller  Failed to provision volume with StorageClass "portworx": services "portworx-service" not found
```

I have one node not well configured in my storage but the pods are ok:
```
/opt/pwx/bin/pxctl status
PX is not running on this host
root@node01:~# /opt/pwx/bin/pxctl status
Status: PX is operational
License: PX-Developer
Node ID: 11d2c5b5-6818-4264-87cf-1e241762c674
        IP: 10.0.1.2
        Local Storage Pool: 1 pool
        POOL    IO_PRIORITY     RAID_LEVEL      USABLE  USED    STATUS  ZONE    REGION
        0       MEDIUM          raid0           20 GiB  2.0 GiB Online  default default
        Local Storage Devices: 1 device
        Device  Path            Media Type              Size            Last-Scan
        0:1     /dev/sda        STORAGE_MEDIUM_MAGNETIC 20 GiB          23 Mar 18 22:12 UTC
        total                   -                       20 GiB
Cluster Summary
        Cluster ID: portworx-storage-0
        Cluster UUID: fb678d93-fcad-4f3b-a85e-188cce5fa9ef
        Nodes: 3 node(s) with storage (2 online)
        IP              ID                                      StorageNode     Used            Capacity        Status
        10.0.1.4        4fd9660b-4206-4b2a-8a41-4e5a96e1d073    Yes             2.0 GiB         20 GiB          Online
        10.0.1.3        3bf347f3-0761-492b-9854-9a0ff17f8c80    Yes             Unavailable     Unavailable     Offline
        10.0.1.2        11d2c5b5-6818-4264-87cf-1e241762c674    Yes             2.0 GiB         20 GiB          Online   (This node)
Global Storage Pool
        Total Used      :  4.0 GiB
        Total Capacity  :  40 GiB
```
*Any idea how to fix this?*

If I create the service with this yml:
```
kind: Service
apiVersion: v1
metadata:
  name: portworx-service
  namespace: kube-system
spec:
  selector:
    name: portworx
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
```
when I try to create the PVC I got:
```
Name:          postgres-data-staging
Namespace:     lb-staging
StorageClass:  portworx
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"postgres-data-staging","namespace":"lb-staging"},"spec":{"access...
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/portworx-volume
Capacity:
Access Modes:
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  0s    persistentvolume-controller  Failed to provision volume with StorageClass "portworx": Get http://10.106.100.183:9001/v1/osd-volumes/versions: dial tcp 10.106.100.183:9001: i/o timeout
```

this are the ports I have working on those nodes related to px
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.0.1.2:9002           0.0.0.0:*               LISTEN      5274/px
tcp        0      0 10.0.1.2:9003           0.0.0.0:*               LISTEN      5257/px-storage
tcp        0      0 0.0.0.0:9004            0.0.0.0:*               LISTEN      4895/px-ns
tcp6       0      0 :::9001                 :::*                    LISTEN      5274/px
tcp6       0      0 :::6060                 :::*                    LISTEN      5274/px
tcp6       0      0 :::9005                 :::*                    LISTEN      5274/px
tcp6       0      0 :::9008                 :::*                    LISTEN      5274/px
tcp6       0      0 :::9009                 :::*                    LISTEN      5257/px-storage
tcp6       0      0 :::9013                 :::*                    LISTEN      4895/px-ns
```

is like 9001 is not exposed properly
