### ISSUE TITLE
Rook deployment and command namespace discrepancy

### ISSUE THREAD

**Issue by GaruGaru** [hobby-kube/guide#45]
In the rook documentation the operator is deployed on the default namespace
```yaml
metadata:
  name: rook-operator
  namespace: default
```
But in the docs the check command uses the rook namespace 

`kubectl -n rook get pods`
