### ISSUE TITLE
Rook & PVC: error opening pool: no such file or directory

### ISSUE THREAD

**Issue by ChrisBuchholz** [hobby-kube/guide#73]
Hi

I'm following the guide, trying to get rook up and running. My cluster is currently on digitalocean and I've added a 1GB volume blocks to all the nodes. I've edited the `storage/cluster.yml` read to this:

```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  backend: ceph
  hostNetwork: false
  dataDirHostPath: /storage
  placement:
    all:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "scsi-0DO_Volume_kube-[0-9]-data"
    config:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
```

I have then tried to run the example commands from the rook-tools pod, but only the first one `kubectl -n rook exec -it rook-tools -- ceph status` works, the rest just hangs. Output from the first is as follows:

```
  cluster:
    id:     6ca887d8-a343-4f4e-8ba4-3c961146596f
    health: HEALTH_WARN
            Reduced data availability: 100 pgs inactive

  services:
    mon: 3 daemons, quorum rook-ceph-mon2,rook-ceph-mon1,rook-ceph-mon0
    mgr: rook-ceph-mgr0(active)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   1 pools, 100 pgs
    objects: 0 objects, 0 bytes
    usage:   0 kB used, 0 kB / 0 kB avail
    pgs:     100.000% pgs unknown
             100 unknown
```

I've also tried to add a persistent volume claim, but it just stays in pending state with the following output from "describing" it:

```
Name:          minio-persistent-storage
Namespace:     default
StorageClass:  rook-block
Status:        Pending
Volume:
Labels:        <none>
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"2641c2c2-732c-11e9-8bd5-f226c23d8711","leaseDurationSeconds":15,"acquireTime":"2019-05-10T14:05:47Z","renewTime":"2019-...
               kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"minio-persistent-storage","namespace":"default"},"s...
               volume.beta.kubernetes.io/storage-provisioner: rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type     Reason              Age                    From                                                                              Message
  ----     ------              ----                   ----                                                                              -------
  Warning  ProvisioningFailed  3m30s (x2 over 3m34s)  rook.io/block rook-operator-bf76bbd9f-zdcn9 2641c2c2-732c-11e9-8bd5-f226c23d8711  Failed to provision volume with StorageClass "rook-block": Failed to create rook block image replicapool/pvc-b59cb43d-732c-11e9-a74c-2646f3d64739: failed to create image pvc-b59cb43d-732c-11e9-a74c-2646f3d64739 in pool replicapool of size 524288000: Failed to complete '': exit status 2. rbd: error opening pool 'replicapool': (2) No such file or directory
. output:
  Normal     Provisioning          3m20s (x3 over 3m34s)  rook.io/block rook-operator-bf76bbd9f-zdcn9 2641c2c2-732c-11e9-8bd5-f226c23d8711  External provisioner is provisioning volume for claim "default/minio-persistent-storage"
  Normal     ExternalProvisioning  2m4s (x25 over 3m31s)  persistentvolume-controller                                                       waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
Mounted By:  <none>
```

Any ideas what is going on?
