### ISSUE TITLE
Rook block device not working for ReadWriteMany

### ISSUE THREAD

**Issue by henrywhitaker3** [hobby-kube/guide#88]
Whe trying to create a `PersistentVolumeClaim` with `ReadWriteMany`, I get the following error when running `kubectl describe pvc <name>`:

```
rook multi node access modes are only supported on rbd `block` type volumes
```

My `cluster:yml`:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook
  namespace: rook
spec:
  backend: ceph
  hostNetwork: false
  dataDirHostPath: /storage
  placement:
    all:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
  mon:
    count: 3
    allowMultiplePerNode: false
  storage:
    useAllNodes: true
    useAllDevices: false
    storeConfig:
      databaseSizeMB: 1024
      journalSizeMB: 1024
    # Uncomment the following line and replace it with the name of block device used for storage:
    deviceFilter: sdb
    # Uncomment the following lines when using a directory for storage:
    #directories:
    #- path: /storage/data
```

`/dev/sdb` it works for `ReadWriteOnce` claims though, any ideas?

(Also, can create a separate issue if needed, but might be worth updating the image used for the ingress controller as the nginx version in the default is fairly old, I used `k8s.gcr.io/ingress-nginx/controller:v0.45.0` as a drop-in replacement)
